<?php

namespace Championnat\sunuChampionnatBundle\Repository;

/**
 * ClassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassementRepository extends \Doctrine\ORM\EntityRepository
{
}
