<?php

namespace Championnat\sunuChampionnatBundle\Repository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends \Doctrine\ORM\EntityRepository {

    //Permet de recupéer toutes les rencontres déja programmées
    public function tousLesRencontres() {

        $qb = $this->createQueryBuilder("ren")
                ->select("ren", "equipe")
                ->from('sunuChampionnatBundle:Rencontre', 'rencontre')
                ->join('ren.equipes', 'equipe');
        return $qb->getQuery()->getResult();
    }
    
     public function uneRencontre($id) {

        $qb = $this->createQueryBuilder("ren")
                ->select("ren", "equipe")
                ->where('ren.id =:id')
                ->setParameter('id', $id)
                ->from('sunuChampionnatBundle:Rencontre', 'rencontre')
                ->join('ren.equipes', 'equipe');
        return $qb->getQuery()->getResult();
    }

}
